# GroupBy and Aggregations

GroupBy operations allow us to summarize and analyze data
by categories such as department, city, or time.

This analysis focuses on understanding patterns in the data
using aggregation techniques such as averages and counts.

In [1]:
import pandas as pd, numpy as np

In [2]:
df = pd.read_csv("data.csv")
df.head(), df.tail()

(   id    name department  age   salary joining_date       city
 0   1    John         IT   28  55000.0   2019-03-15      Delhi
 1   2    Neha      SALES   35  50000.0   2018-01-07  Bangalore
 2   3  Vikram         IT   30  72000.0   2022-11-20    Chennai
 3   4   Sonia         HR   29  58000.0   2021-12-09     Mumbai
 4   5   Rahul      SALES   29  45000.0   2017-10-04      Delhi,
     id    name department  age   salary joining_date       city
 36  37  Kavita         HR   26  53000.0   2021-05-10  Bangalore
 37  38   Suraj      SALES   31  56000.0   2017-08-14       Pune
 38  39   Divya         HR   29  55000.0   2019-07-19       Pune
 39  40     Raj    FINANCE   29  77000.0   2019-05-15    Chennai
 40  41   Heena         HR   30  58000.0   2020-02-20      Delhi)

## Basic GroupBy
Group by Department, then calculate average Salary for each group.

In [3]:
df.groupby('department')['salary'].mean()

department
FINANCE    82444.444444
HR         54500.000000
IT         66250.000000
SALES      51000.000000
Name: salary, dtype: float64

## Common Aggregation Functions

### Average Salary per City

In [4]:
df.groupby("city")["salary"].mean()

city
Bangalore    66500.000000
Chennai      72428.571429
Delhi        61000.000000
Mumbai       55375.000000
Pune         64285.714286
Name: salary, dtype: float64

### Total Salary by Department

In [5]:
df.groupby("department")["salary"].sum()

department
FINANCE    742000.0
HR         545000.0
IT         795000.0
SALES      510000.0
Name: salary, dtype: float64

### Total Employees by City

In [6]:
df.groupby("city")["salary"].count()

city
Bangalore     6
Chennai       7
Delhi        13
Mumbai        8
Pune          7
Name: salary, dtype: int64

### Maximum Salary per City

In [7]:
df.groupby("city")["salary"].max()

city
Bangalore    82000.0
Chennai      95000.0
Delhi        88000.0
Mumbai       68000.0
Pune         92000.0
Name: salary, dtype: float64

### Minimum Salary per City

In [8]:
df.groupby("city")["salary"].min()

city
Bangalore    50000.0
Chennai      55000.0
Delhi        45000.0
Mumbai       49000.0
Pune         48000.0
Name: salary, dtype: float64

## Multiple Aggregations

In [9]:
df.groupby('department')['salary'].agg(['mean', 'min', 'max', 'count'])

                    mean      min      max  count
department
FINANCE     82444.444444  72000.0  95000.0      9
HR          54500.000000  49000.0  60000.0     10
IT          66250.000000  55000.0  72000.0     12
SALES       51000.000000  45000.0  56000.0     10

In [10]:
df.groupby('department')['salary'].agg(['mean', 'median'])

                    mean   median
department
FINANCE     82444.444444  81000.0
HR          54500.000000  54000.0
IT          66250.000000  68000.0
SALES       51000.000000  50000.0

## GroupBy on Multiple Columns

In [11]:
df.groupby(['department', 'city'])['salary'].mean()

department  city
FINANCE     Bangalore    81000.000000
            Chennai      86000.000000
            Delhi        80333.333333
            Pune         83500.000000
HR          Bangalore    53000.000000
            Delhi        53000.000000
            Mumbai       54750.000000
            Pune         57000.000000
IT          Bangalore    67000.000000
            Chennai      70000.000000
            Delhi        62000.000000
            Mumbai       68000.000000
            Pune         65000.000000
SALES       Bangalore    50000.000000
            Chennai      55000.000000
            Delhi        48333.333333
            Mumbai       52000.000000
            Pune         52000.000000
Name: salary, dtype: float64

## Custom Aggregations with .agg()

In [12]:
df.groupby('department').agg({
    'salary': 'mean',
    'age': 'median'
})

                  salary   age
department
FINANCE     82444.444444  32.0
HR          54500.000000  28.5
IT          66250.000000  28.0
SALES       51000.000000  30.0

## Named Aggregation (Cleanest way)

In [13]:
# Better than dictionary agg
df.groupby('department').agg(
    avg_salary=('salary', 'mean'),
    max_age=('age', 'max'),
    employee_count=('id', 'count')
                            )

              avg_salary  max_age  employee_count
department
FINANCE     82444.444444       40               9
HR          54500.000000       30              10
IT          66250.000000       32              12
SALES       51000.000000       35              10

## Time-based GroupBy

In [14]:
df['year'] = pd.to_datetime(df['joining_date']).dt.year
df.groupby('year')['salary'].mean()

year
2015    92000.000000
2016    81500.000000
2017    59750.000000
2018    66750.000000
2019    66166.666667
2020    58428.571429
2021    59000.000000
2022    57600.000000
2023    68666.666667
Name: salary, dtype: float64

## Reset Index

In [15]:
df.groupby('department')['salary'].mean().reset_index()

  department        salary
0    FINANCE  82444.444444
1         HR  54500.000000
2         IT  66250.000000
3      SALES  51000.000000

## Summary
- .groupby() helps you summarize large datasets by category
- Aggregations simplify complex datasets
- Use mean() , sum() , count() , .agg() for custom metrics