## Pivot Tables in Pandas

Pivot tables summarize data by transforming rows into structured
analytical tables using aggregation functions.

Pivot tables internally use groupby and aggregation but reshape results into a matrix format.

## How it works:
`pivot()` takes a long-format DataFrame and turns it into a wide-format
DataFrame by specifying which columns will become the new columns, the
rows, and the values.

In [2]:
import pandas as pd, numpy as np

In [3]:
df = pd.read_csv("data.csv")
df.head(), df.tail()

(   id    name department  age   salary joining_date       city
 0   1    John         IT   28  55000.0   2019-03-15      Delhi
 1   2    Neha      SALES   35  50000.0   2018-01-07  Bangalore
 2   3  Vikram         IT   30  72000.0   2022-11-20    Chennai
 3   4   Sonia         HR   29  58000.0   2021-12-09     Mumbai
 4   5   Rahul      SALES   29  45000.0   2017-10-04      Delhi,
     id    name department  age   salary joining_date       city
 36  37  Kavita         HR   26  53000.0   2021-05-10  Bangalore
 37  38   Suraj      SALES   31  56000.0   2017-08-14       Pune
 38  39   Divya         HR   29  55000.0   2019-07-19       Pune
 39  40     Raj    FINANCE   29  77000.0   2019-05-15    Chennai
 40  41   Heena         HR   30  58000.0   2020-02-20      Delhi)

## Basic Pivot Table

In [3]:
df.pivot_table(
    values='salary',
    index='department',
    aggfunc='mean'
              )

                  salary
department
FINANCE     82444.444444
HR          54500.000000
IT          66250.000000
SALES       51000.000000

## Pivot with Rows and Column

In [4]:
df.pivot_table(
    values='salary',
    index='department',
    columns='city',
    aggfunc='mean'
              )

city        Bangalore  Chennai         Delhi   Mumbai     Pune
department
FINANCE       81000.0  86000.0  80333.333333      NaN  83500.0
HR            53000.0      NaN  53000.000000  54750.0  57000.0
IT            67000.0  70000.0  62000.000000  68000.0  65000.0
SALES         50000.0  55000.0  48333.333333  52000.0  52000.0

This type of table is commonly used in financial and HR reports
to compare performance across departments and locations.

## Multiple Aggregations
Multiple aggregation functions create hierarchical column labels.

In [8]:
df.pivot_table(
    values='salary',
    index='department',
    aggfunc=['mean', 'max', 'min', 'count']
              )

                    mean      max      min  count
                  salary   salary   salary salary
department
FINANCE     82444.444444  95000.0  72000.0      9
HR          54500.000000  60000.0  49000.0     10
IT          66250.000000  72000.0  55000.0     12
SALES       51000.000000  56000.0  45000.0     10

pivot_table is built on groupby internally,
making it efficient for large datasets.

## Multiple Value Columns

In [9]:
df.pivot_table(
    values=['salary', 'age'],
    index='department',
    aggfunc='mean'
              )

                  age        salary
department
FINANCE     32.666667  82444.444444
HR          27.600000  54500.000000
IT          27.916667  66250.000000
SALES       30.000000  51000.000000

## Handling Missing Values in Pivot

In [10]:
df.pivot_table(
    values='salary',
    index='department',
    columns='city',
    aggfunc='mean',
    fill_value=0
              )

city        Bangalore  Chennai         Delhi   Mumbai     Pune
department
FINANCE       81000.0  86000.0  80333.333333      0.0  83500.0
HR            53000.0      0.0  53000.000000  54750.0  57000.0
IT            67000.0  70000.0  62000.000000  68000.0  65000.0
SALES         50000.0  55000.0  48333.333333  52000.0  52000.0

## Pivot vs GroupBy
| GroupBy                  | Pivot Table                |
| ------------------------ | -------------------------- |
| Flexible                 | Structured output          |
| Good for analysis        | Good for reporting         |
| Returns Series/DataFrame | Returns matrix-style table |

## Summary
- pivot_table combines grouping and reshaping
- It supports aggregation
- It handles duplicate entries
- It is ideal for summary reports