# Reshaping Data using Melt and Pivot

In [1]:
import pandas as pd, numpy as np

In [2]:
# Sample DataFrame
data = {
'Name': ['Pooja', 'Riya', 'Vijay', 'Raj', 'Ajay'],
'Math': [81, 88, 82, 94, 87],
'Science': [90, 92, 97, 96, 79],
'English': [80, 86, 84, 98, 78]
}
df = pd.DataFrame(data)
df

    Name  Math  Science  English
0  Pooja    81       90       80
1   Riya    88       92       86
2  Vijay    82       97       84
3    Raj    94       96       98
4   Ajay    87       79       78

## `melt()` — Wide to Long
The melt() method in Pandas is used to unpivot a DataFrame from wide format
to long format. In other words, it takes columns that represent different variables
and combines them into key-value pairs

### Parameters
- `id_vars` : The columns that you want to keep fixed (these columns will remain
as identifiers).
- `value_vars` : The columns you want to unpivot (the ones you want to “melt”
into a single column).
- `var_name` : The name to use for the new column that will contain the names of
the melted columns (default is 'variable' ).
- `value_name` : The name to use for the new column that will contain the values
from the melted columns (default is 'value' ).
- `col_level` : Used for multi-level column DataFrames.

In [3]:
melt_data = df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")
melt_data

     Name  Subject  Score
0   Pooja     Math     81
1    Riya     Math     88
2   Vijay     Math     82
3     Raj     Math     94
4    Ajay     Math     87
5   Pooja  Science     90
6    Riya  Science     92
7   Vijay  Science     97
8     Raj  Science     96
9    Ajay  Science     79
10  Pooja  English     80
11   Riya  English     86
12  Vijay  English     84
13    Raj  English     98
14   Ajay  English     78

### Why Use `melt()`?
- **Data normalization**: Helps in transforming data for statistical modeling and
data visualization.
- **Pivot tables**: Many times, plotting functions or statistical models work better
with long-format data.

## `pivot()` — Long to Wide
The pivot() function in Pandas is used to reshape data, specifically to turn longformat data into wide-format data. This is the reverse operation of melt() .

### Parameters
- `index` : The column whose unique values will become the rows of the new
DataFrame.
- `columns` : The column whose unique values will become the columns of the
new DataFrame.
- `values` : The column whose values will fill the new DataFrame. These will
become the actual data (values in the table).

In [4]:
melt_data.pivot(index="Name", columns="Subject", values="Score")

Subject  English  Math  Science
Name
Ajay          78    87       79
Pooja         80    81       90
Raj           98    94       96
Riya          86    88       92
Vijay         84    82       97

### Why use pivot() ?
- **Better data structure**: It makes data easier to analyze when you have
categories that you want to split into multiple columns.
- **Easier visualization**: Often, you want to represent data in a format where
categories are split across columns (for example, when creating pivot tables
for reporting).
- **Aggregating data**: You can perform aggregations (like sum , mean , etc.) to
group values before pivoting.

## pivot_table() to handle duplicates

In [5]:
# Sample DataFrame
data = {
'Name': ['Pooja', 'Riya', 'Vijay', 'Pooja', 'Riya', 'Vijay', 'Pooja', 'Riya', 'Vijay'],
'Subject': ['Math', 'Math', 'Math', 'Math', 'Science', 'Science', 'Math', 'Science', 'Science'],
'Score': [81, 88, 82, 94, 87, 90, 92, 97, 96],
}
df = pd.DataFrame(data)
df

    Name  Subject  Score
0  Pooja     Math     81
1   Riya     Math     88
2  Vijay     Math     82
3  Pooja     Math     94
4   Riya  Science     87
5  Vijay  Science     90
6  Pooja     Math     92
7   Riya  Science     97
8  Vijay  Science     96

### Notes
**Duplicate Entries**: If you have multiple rows with the same combination of
index and columns , `pivot()` will raise an **error**. In such cases, you should use
`pivot_table()` (which can handle duplicate entries by aggregating them).

## `pivot_table()` to handle duplicates
We can use `pivot_table()` to aggregate values (e.g., taking the mean for
duplicate entries):

In [6]:
df.pivot_table(index="Name", columns="Subject", values="Score", aggfunc="mean")

Subject  Math  Science
Name
Pooja    89.0      NaN
Riya     88.0     92.0
Vijay    82.0     93.0

In this case, 
the Math score for Pooja is averaged (81 + 94 + 92) / 3 = 89.0. If a cell is
empty, it means there was no value for that combination.

## When to Use
- melt → preparing data for analysis
- pivot → preparing summary reports

## Summary:
- Use `melt()` to go long, `pivot()` to go wide
- `pivot()` is used to turn long-format data into wide-format by spreading
unique column values into separate columns.
- If there are **duplicate values** for a given combination of index and columns ,
you should use `pivot_table()` with an aggregation function to handle the
duplicates.