# Sorting & Ranking
Sorting and ranking allow us to organize data and identify
top or bottom performers in a dataset.

In [1]:
import pandas as pd, numpy as np

In [2]:
df = pd.read_csv("Data.csv")
df.head(15)

    id    name department  age   salary joining_date       city
0    1    John         IT   28  55000.0   2019-03-15      Delhi
1    2    Neha      SALES   35  50000.0   2018-01-07  Bangalore
2    3  Vikram         IT   30  72000.0   2022-11-20    Chennai
3    4   Sonia         HR   29  58000.0   2021-12-09     Mumbai
4    5   Rahul      SALES   29  45000.0   2017-10-04      Delhi
5    6   Priya         IT   24  65000.0   2023-01-22       Pune
6    7   Karan    FINANCE   32  80000.0   2019-05-12  Bangalore
7    8   Sneha         HR   27  52000.0   2021-03-18     Mumbai
8    9   Rohan         IT   31  68000.0   2021-06-25      Delhi
9   10  Anjali      SALES   26  48000.0   2022-02-14       Pune
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai
11  12   Megha         IT   29  62000.0   2020-12-12      Delhi
12  13   Arjun      SALES   33  54000.0   2018-05-20     Mumbai
13  14   Pooja         HR   28  51000.0   2021-05-08      Delhi
14  15    Aman         IT   25  70000.0   2023-01-15  Bangalore

## Sorting

### Sort by Values

In [3]:
df.sort_values("name").head(10) # Ascending sort

    id    name department  age   salary joining_date       city
32  33   Abhay    FINANCE   38  92000.0   2015-12-12       Pune
29  30   Aditi      SALES   30  55000.0   2019-02-28    Chennai
30  31   Akash         IT   26  64000.0   2021-07-07  Bangalore
14  15    Aman         IT   25  70000.0   2023-01-15  Bangalore
18  19    Amit      SALES   25  50000.0   2021-01-10      Delhi
9   10  Anjali      SALES   26  48000.0   2022-02-14       Pune
12  13   Arjun      SALES   33  54000.0   2018-05-20     Mumbai
25  26   Aryan         HR   29  59000.0   2020-05-11       Pune
33  34   Deepa      SALES   27  49000.0   2020-09-09     Mumbai
38  39   Divya         HR   29  55000.0   2019-07-19       Pune

In [4]:
df.sort_values("name", ascending=False).head(10) # Descending

    id    name department  age   salary joining_date       city
31  32    Zoya         HR   25  50000.0   2022-06-18      Delhi
20  21    Yash         IT   26  63000.0   2021-01-12      Delhi
2    3  Vikram         IT   30  72000.0   2022-11-20    Chennai
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai
19  20    Tara    FINANCE   31  82000.0   2018-12-04  Bangalore
37  38   Suraj      SALES   31  56000.0   2017-08-14       Pune
3    4   Sonia         HR   29  58000.0   2021-12-09     Mumbai
7    8   Sneha         HR   27  52000.0   2021-03-18     Mumbai
26  27  Simran         IT   32  68000.0   2016-05-14     Mumbai
15  16  Shweta    FINANCE   29  75000.0   2019-11-11       Pune

In [5]:
df.sort_values(["department", "age"], inplace=True) # Sort by multiple columns
df.head(10)

    id    name department  age   salary joining_date       city
27  28   Kabir    FINANCE   27  72000.0   2021-10-20      Delhi
15  16  Shweta    FINANCE   29  75000.0   2019-11-11       Pune
39  40     Raj    FINANCE   29  77000.0   2019-05-15    Chennai
19  20    Tara    FINANCE   31  82000.0   2018-12-04  Bangalore
6    7   Karan    FINANCE   32  80000.0   2019-05-12  Bangalore
35  36  Pankaj    FINANCE   33  81000.0   2018-11-22      Delhi
23  24  Manish    FINANCE   35  88000.0   2017-01-25      Delhi
32  33   Abhay    FINANCE   38  92000.0   2015-12-12       Pune
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai
17  18   Nisha         HR   24  49000.0   2022-05-05     Mumbai

`df.sort_values(["department", "age"])` sorts the DataFrame first by the **“department”** column, and
if there are ties (i.e., two or more rows with the same “department”), it will sort by the
**“age”** column.

## Sort by Index

The `df.sort_index()` function is used to sort the DataFrame based on its index
values. If the index is not in a sequential order (e.g., you have dropped rows or
performed other operations that change the index), you can use sort_index() to
restore it to a sorted order

In [6]:
df.sort_index().head(15)

    id    name department  age   salary joining_date       city
0    1    John         IT   28  55000.0   2019-03-15      Delhi
1    2    Neha      SALES   35  50000.0   2018-01-07  Bangalore
2    3  Vikram         IT   30  72000.0   2022-11-20    Chennai
3    4   Sonia         HR   29  58000.0   2021-12-09     Mumbai
4    5   Rahul      SALES   29  45000.0   2017-10-04      Delhi
5    6   Priya         IT   24  65000.0   2023-01-22       Pune
6    7   Karan    FINANCE   32  80000.0   2019-05-12  Bangalore
7    8   Sneha         HR   27  52000.0   2021-03-18     Mumbai
8    9   Rohan         IT   31  68000.0   2021-06-25      Delhi
9   10  Anjali      SALES   26  48000.0   2022-02-14       Pune
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai
11  12   Megha         IT   29  62000.0   2020-12-12      Delhi
12  13   Arjun      SALES   33  54000.0   2018-05-20     Mumbai
13  14   Pooja         HR   28  51000.0   2021-05-08      Delhi
14  15    Aman         IT   25  70000.0   2023-01-15  Bangalore

## Ranking
Ranking allows organizations to identify top performers,
high-value customers, or priority segments.

When ties occur, the ranking method determines whether
gaps appear in the ranking sequence.

### Average Method(Default)
Assigns the average rank of the tied values. Ranks may have decimal places.

In [7]:
df["Rank"] = df["salary"].rank(ascending=False) # 9.5 (average of 9 and 10)
df.sort_values("Rank").head(10)

    id    name department  age   salary joining_date       city  Rank
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai   1.0
32  33   Abhay    FINANCE   38  92000.0   2015-12-12       Pune   2.0
23  24  Manish    FINANCE   35  88000.0   2017-01-25      Delhi   3.0
19  20    Tara    FINANCE   31  82000.0   2018-12-04  Bangalore   4.0
35  36  Pankaj    FINANCE   33  81000.0   2018-11-22      Delhi   5.0
6    7   Karan    FINANCE   32  80000.0   2019-05-12  Bangalore   6.0
39  40     Raj    FINANCE   29  77000.0   2019-05-15    Chennai   7.0
15  16  Shweta    FINANCE   29  75000.0   2019-11-11       Pune   8.0
27  28   Kabir    FINANCE   27  72000.0   2021-10-20      Delhi   9.5
2    3  Vikram         IT   30  72000.0   2022-11-20    Chennai   9.5

### First Method
Assigns unique ranks based on the order of appearance in the array. No ranks are skipped.

In [8]:
df["Rank"] = df["salary"].rank(method="first", ascending=False) # 1, 2, 3 (assigned in order of appearance)
df.sort_values("Rank").head(10)

    id    name department  age   salary joining_date       city  Rank
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai   1.0
32  33   Abhay    FINANCE   38  92000.0   2015-12-12       Pune   2.0
23  24  Manish    FINANCE   35  88000.0   2017-01-25      Delhi   3.0
19  20    Tara    FINANCE   31  82000.0   2018-12-04  Bangalore   4.0
35  36  Pankaj    FINANCE   33  81000.0   2018-11-22      Delhi   5.0
6    7   Karan    FINANCE   32  80000.0   2019-05-12  Bangalore   6.0
39  40     Raj    FINANCE   29  77000.0   2019-05-15    Chennai   7.0
15  16  Shweta    FINANCE   29  75000.0   2019-11-11       Pune   8.0
27  28   Kabir    FINANCE   27  72000.0   2021-10-20      Delhi   9.0
2    3  Vikram         IT   30  72000.0   2022-11-20    Chennai  10.0

### Dense Method
Assigns ranks using consecutive integers with no gaps, even in the presence of ties.

In [9]:
df["Rank"] = df["salary"].rank(method="dense", ascending=False) # 9, 9 (next rank is 10)
df.sort_values("Rank").head(10)

    id    name department  age   salary joining_date       city  Rank
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai   1.0
32  33   Abhay    FINANCE   38  92000.0   2015-12-12       Pune   2.0
23  24  Manish    FINANCE   35  88000.0   2017-01-25      Delhi   3.0
19  20    Tara    FINANCE   31  82000.0   2018-12-04  Bangalore   4.0
35  36  Pankaj    FINANCE   33  81000.0   2018-11-22      Delhi   5.0
6    7   Karan    FINANCE   32  80000.0   2019-05-12  Bangalore   6.0
39  40     Raj    FINANCE   29  77000.0   2019-05-15    Chennai   7.0
15  16  Shweta    FINANCE   29  75000.0   2019-11-11       Pune   8.0
27  28   Kabir    FINANCE   27  72000.0   2021-10-20      Delhi   9.0
2    3  Vikram         IT   30  72000.0   2022-11-20    Chennai   9.0

### Max Method
Assigns the highest rank in the group to all tied values. Ranks after the tie are skipped.

In [10]:
df["Rank"] = df["salary"].rank(method="max", ascending=False) # Skip 9 (next rank is 10)
df.sort_values("Rank").head(10)

    id    name department  age   salary joining_date       city  Rank
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai   1.0
32  33   Abhay    FINANCE   38  92000.0   2015-12-12       Pune   2.0
23  24  Manish    FINANCE   35  88000.0   2017-01-25      Delhi   3.0
19  20    Tara    FINANCE   31  82000.0   2018-12-04  Bangalore   4.0
35  36  Pankaj    FINANCE   33  81000.0   2018-11-22      Delhi   5.0
6    7   Karan    FINANCE   32  80000.0   2019-05-12  Bangalore   6.0
39  40     Raj    FINANCE   29  77000.0   2019-05-15    Chennai   7.0
15  16  Shweta    FINANCE   29  75000.0   2019-11-11       Pune   8.0
27  28   Kabir    FINANCE   27  72000.0   2021-10-20      Delhi  10.0
2    3  Vikram         IT   30  72000.0   2022-11-20    Chennai  10.0

### Min Method
Assigns the lowest rank in the group to all tied values. Ranks after the tie are skipped. (e.g., 2 for a tie in positions 2 and 3).

In [11]:
df["Rank"] = df["salary"].rank(method="min", ascending=False) # Skip 10 (next rank is 11)
df.sort_values("Rank").head(12)

    id    name department  age   salary joining_date       city  Rank
10  11   Varun    FINANCE   40  95000.0   2016-10-30    Chennai   1.0
32  33   Abhay    FINANCE   38  92000.0   2015-12-12       Pune   2.0
23  24  Manish    FINANCE   35  88000.0   2017-01-25      Delhi   3.0
19  20    Tara    FINANCE   31  82000.0   2018-12-04  Bangalore   4.0
35  36  Pankaj    FINANCE   33  81000.0   2018-11-22      Delhi   5.0
6    7   Karan    FINANCE   32  80000.0   2019-05-12  Bangalore   6.0
39  40     Raj    FINANCE   29  77000.0   2019-05-15    Chennai   7.0
15  16  Shweta    FINANCE   29  75000.0   2019-11-11       Pune   8.0
27  28   Kabir    FINANCE   27  72000.0   2021-10-20      Delhi   9.0
2    3  Vikram         IT   30  72000.0   2022-11-20    Chennai   9.0
34  35   Sahil         IT   29  71000.0   2023-01-04    Chennai  11.0
14  15    Aman         IT   25  70000.0   2023-01-15  Bangalore  12.0

## Ranking Within Groups

In [12]:
df['dept_rank'] = df.groupby('department')['salary'] \
                     .rank(ascending=False)
df.sort_values('dept_rank').head(10)

,id,name,department,age,salary,joining_date,city,Rank,dept_rank
10,11,Varun,FINANCE,40,95000.0,2016-10-30,Chennai,1.0,1.0
28,29,Riya,HR,29,60000.0,2020-05-15,Mumbai,21.0,1.0
2,3,Vikram,IT,30,72000.0,2022-11-20,Chennai,9.0,1.0
37,38,Suraj,SALES,31,56000.0,2017-08-14,Pune,25.0,1.0
25,26,Aryan,HR,29,59000.0,2020-05-11,Pune,22.0,2.0
34,35,Sahil,IT,29,71000.0,2023-01-04,Chennai,11.0,2.0
29,30,Aditi,SALES,30,55000.0,2019-02-28,Chennai,26.0,2.0
32,33,Abhay,FINANCE,38,92000.0,2015-12-12,Pune,2.0,2.0
14,15,Aman,IT,25,70000.0,2023-01-15,Bangalore,12.0,3.0
12,13,Arjun,SALES,33,54000.0,2018-05-20,Mumbai,29.0,3.0

## Top N Selection
nlargest() is more efficient than sorting the entire dataset
when only top records are required.

### Top 3 by salary

In [13]:
df.nlargest(3, 'salary')

    id    name department  age   salary joining_date     city  Rank  dept_rank
10  11   Varun    FINANCE   40  95000.0   2016-10-30  Chennai   1.0        1.0
32  33   Abhay    FINANCE   38  92000.0   2015-12-12     Pune   2.0        2.0
23  24  Manish    FINANCE   35  88000.0   2017-01-25    Delhi   3.0        3.0

### Last Top 3 by salary

In [14]:
df.nsmallest(3, 'salary')

    id    name department  age   salary joining_date    city  Rank  dept_rank
4    5   Rahul      SALES   29  45000.0   2017-10-04   Delhi  41.0       10.0
9   10  Anjali      SALES   26  48000.0   2022-02-14    Pune  40.0        9.0
17  18   Nisha         HR   24  49000.0   2022-05-05  Mumbai  38.0       10.0

## Summary
- sort_values organizes data
- rank assigns order positions
- groupby + rank enables category-based ranking
- nlargest is efficient for top-N queries